import { Dictionary } from '../http-common';
import { HttpEndpointFunction } from '../http-endpoint';
import { HttpClientBase } from './http-client-base';
import {
  HttpClient,
  HttpClientSettings,
  HttpClientSettingsWithBody,
  HttpClientSetupFunction,
  HttpClientResponseResult,
} from './http-client';

export abstract class HttpClientDecorator<
  P extends Dictionary = {},
  Q extends Dictionary = {},
  B extends object | void = void,
> implements HttpClient<P, Q, B> {

  /** The http client instance being decorated */
  protected base: HttpClientBase<P, Q, B>;

  /**
   * Creates a new instance with the same settings.
   * 
   * @returns
   * A new instance with the same settings.
   */
  clone(): HttpClient<P, Q, B> {
    return this.base.clone();
  }

  /**
   * Accepts a function that interacts with this instance.
   * 
   * @param setupFn
   * A function that accepts HttpClient as first parameter.
   * @returns
   * This instance.
   */
  setup(setupFn: HttpClientSetupFunction<P>): HttpClient<P, Q, B> {
    return this.base.setup(setupFn);
  }

  /**
   * Sets a base service URL to make requests.
   * 
   * @param serviceUrl
   * An url that will be used as the base url on all requests.
   * @returns
   * This instance.
   */
  setServiceUrl(serviceUrl: string): HttpClient<P, Q, B> {
    return this.base.setServiceUrl(serviceUrl);
  }
  
  /**
   * Sets an endpoint function, it will be filled with the params on each request.
   * 
   * @param endpointFn
   * A function that accepts parameters and returns an string as endpoint.
   * @returns
   * This instance.
   */
  setEndpoint(endpointFn: HttpEndpointFunction<P>): HttpClient<P, Q, B> {
    return this.base.setEndpoint(endpointFn);
  }

  /**
   * Sets an authorization to be sent on the HTTP request headers.
   * 
   * @param authorization
   * An authroization header value.
   * @returns
   * This instance.
   */
  setAuthorization(authorization: string): HttpClient<P, Q, B> {
    return this.base.setAuthorization(authorization);
  }

  /**
   * Sets a basic authorization to be sent on the HTTP request headers.
   * 
   * @param token
   * The suffix after "Basic".
   * @returns
   * This instance.
   */
  setBasicAuth(token: string): HttpClient<P, Q, B> {
    return this.base.setBasicAuth(token);
  }

  /**
   * Sets a bearer authorization to be sent on the HTTP request headers.
   * 
   * @param token
   * The suffix after "Bearer".
   * @returns
   * This instance.
   */
  setBearerAuth(token: string): HttpClient<P, Q, B> {
    return this.base.setBearerAuth(token);
  }

  /**
   * Sets a basic authorization with the given username and password.
   * 
   * @param username
   * An username.
   * @param password
   * A password.
   * @returns
   * This instance.
   */
  setBasicAuthCredentials(username: string, password: string): HttpClient<P, Q, B> {
    return this.base.setBasicAuthCredentials(username, password);
  }

  /**
   * An object to be parsed into URL parameters, it will be injected into the
   * endpoint function.
   * 
   * @param params
   * An object to be parsed into URL params.
   * @param replace
   * Replaces the whole params if true, will merge otherwise.
   * @returns
   * This instance.
   */
  setParams(params: P, replace: boolean): HttpClient<P, Q, B> {
    return this.base.setParams(params, replace);
  }

  /**
   * An object to be parsed into a query string.
   * if some property values is an array then will be repeated:
   * { item: [1, 2, 3, 4] } --> ?item=1&item=2&item=3&item=4
   * 
   * @param query
   * An object to be parsed into a query string.
   * @param replace
   * Replaces the whole query if true, will merge otherwise.
   * @returns
   * This instance.
   */
  setQuery(query: Q, replace: boolean): HttpClient<P, Q, B> {
    return this.base.setQuery(query, replace);
  }

  /**
   * An object to be assigned into HTTP headers.
   * 
   * @param headers
   * An object to be assigned into HTTP headers.
   * @param replace
   * Replaces the whole headers if true, will merge otherwise.
   * @returns
   * This instance.
   */
  setHeaders(headers: Dictionary, replace: boolean): HttpClient<P, Q, B> {
    return this.base.setHeaders(headers, replace);
  }

  /**
   * A signal to abort all the HTTP requests generated by this instance.
   *
   * @param signal
   * An abort signal.
   * @returns
   * This instance.
   */
  setSignal(signal: AbortSignal): HttpClient<P, Q, B> {
    return this.base.setSignal(signal);
  }

  /**
   * Performs a GET request.
   * 
   * @param settings
   * Settings to override the general settings.
   * @returns
   * A response object with the parsed content.
   */
  abstract get<
    C,
    PE extends P = P,
    QE extends Q = Q,
  >(settings: HttpClientSettings<PE, QE>): Promise<HttpClientResponseResult<C, PE>>;

  /**
   * Performs a POST request.
   * 
   * @param settings
   * Settings to override the general settings.
   * @returns
   * A response object with the parsed content.
   */
  abstract post<
    C,
    PE extends P = P,
    QE extends Q = Q,
    BE extends B = B,
  >(settings: HttpClientSettingsWithBody<PE, QE, BE>): Promise<HttpClientResponseResult<C, PE>>;

  /**
   * Performs a PUT request.
   * 
   * @param settings
   * Settings to override the general settings.
   * @returns
   * A response object with the parsed content.
   */
  abstract put<
    C,
    PE extends P = P,
    QE extends Q = Q,
    BE extends B = B,
  >(settings: HttpClientSettingsWithBody<PE, QE, BE>): Promise<HttpClientResponseResult<C, PE>>;

  /**
   * Performs a DELETE request.
   * 
   * @param settings
   * Settings to override the general settings.
   * @returns
   * A response object with the parsed content.
   */
  abstract del<
    C,
    PE extends P = P,
    QE extends Q = Q,
  >(settings: HttpClientSettings<PE, QE>): Promise<HttpClientResponseResult<C, PE>>;
}
